import { useState } from "react";
import { stations, recentCaptures } from "../data/mockData";

export default function CameraTrapsScreen() {
  const [path, setPath] = useState("");
  const [running, setRunning] = useState(false);
  const [progress, setProgress] = useState(0);
  function process() { setRunning(true); setProgress(0); let p = 0; const timer = window.setInterval(() => { p += 12; setProgress(Math.min(p,100)); if (p >= 100) { window.clearInterval(timer); setRunning(false); } }, 180); }
  return <div className="p-6 space-y-5 max-w-[1300px]"><div><div className="label-eyebrow">Field image intake</div><h2 className="text-2xl font-semibold mt-1">Camera Traps</h2><p className="text-[12px] text-inkMuted mt-1">Paste a local folder or file path. R.O.A.R processes tiger camera-trap images locally.</p></div><div className="panel p-5"><div className="grid grid-cols-1 xl:grid-cols-[1fr_auto] gap-3"><input value={path} onChange={e=>setPath(e.target.value)} placeholder="C:\\Pench\\CameraTraps\\C07 or D:\\image.jpg" className="px-3 py-2 rounded bg-panelAlt border border-border text-[11px] font-mono"/><button onClick={process} disabled={!path || running} className="px-4 py-2 rounded bg-amber text-bg text-[11px] font-semibold disabled:opacity-40">{running?"Processing...":"Process local path"}</button></div>{running && <div className="mt-4"><div className="flex justify-between text-[10px] text-inkMuted"><span>Pre-processing → blank filtering → tiger detection → stripe matching</span><span>{progress}%</span></div><div className="h-2 bg-panelAlt rounded mt-1 overflow-hidden"><div className="h-full bg-amber" style={{width:`${progress}%`}}/></div></div>}</div><div className="grid grid-cols-2 xl:grid-cols-4 gap-3"><div className="panel p-4"><div className="label-eyebrow">Registered cameras</div><div className="text-2xl font-mono mt-2">{stations.length}</div></div><div className="panel p-4"><div className="label-eyebrow">Tiger captures</div><div className="text-2xl font-mono mt-2">{recentCaptures.length}</div></div><div className="panel p-4"><div className="label-eyebrow">Core cameras</div><div className="text-2xl font-mono mt-2">{stations.filter(s=>s.zone==='core').length}</div></div><div className="panel p-4"><div className="label-eyebrow">Buffer cameras</div><div className="text-2xl font-mono mt-2">{stations.filter(s=>s.zone==='buffer').length}</div></div></div><div className="panel p-4"><div className="label-eyebrow">Recent tiger captures</div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3 mt-3">{recentCaptures.map(c=><div key={c.id} className="border border-border rounded-lg p-3 bg-panelAlt"><div className="text-[12px] font-mono text-amber">{c.tigerId}</div><div className="text-[10px] text-inkMuted mt-1">Camera {c.stationId}</div><div className="text-[9px] text-inkFaint mt-2">{new Date(c.timestamp).toLocaleString()}</div></div>)}</div></div></div>;
}
